[package]
name = "speed"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
futures = "0.3.31"
rand = "0.8.5"
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = "0.26.1"
